Project.toml
src/MAGEMinApp.jl
src/MAGEMinApp_Callbacks.jl
src/MAGEMinApp_functions.jl

- added option to export necessary data for geodynamic modelling

MAGEMinApp v0.1.9

---

Project.toml
src/Tab_Simulation.jl

- corrected issue with minimum number of pseudocompounds for fluid which was leading to segmentation fault when computing system specific heat capacity

MAGEMinApp 0.2.0

---

Project.toml
src/AMR/MAGEMiN_utils.jl
src/PhaseDiagram_functions.jl
src/Tab_PhaseDiagram.jl
src/Tab_PhaseDiagram_Callbacks.jl
src/Tab_Simulation.jl
src/Tab_Simulation_Callbacks.jl
src/appData.jl
test/tests.jl

- Changed option to save all data points to an csv file through Julia instead of a "download" through the web browser. This fixes a timeout issue when the number of points was too large > 5k

MAGEMinApp v0.2.1

---

Project.toml
src/IsentropicPaths_functions.jl
src/MAGEMinApp.jl
src/PTXpaths_functions.jl
src/PhaseDiagram_functions.jl
src/Tab_PTXpaths.jl
src/Tab_PTXpaths_Callbacks.jl

- Added assimilation option for PTX paths

MAGEMinApp v0.2.7

---

Project.toml
src/MAGEMinApp.jl

- Correction of zircon saturation for Crispy and Berry 2022
- Added tests for zircon saturation formulations

MAGEMinApp v0.3.2

---

Project.toml
src/AMR/MAGEMiN_utils.jl
src/MAGEMinApp.jl

- Corrects problem when saving PTX path information as table

MAGEMinApp v0.3.3

---

Project.toml
src/MAGEMinApp.jl
src/PTXpaths_functions.jl
src/Tab_PTXpaths.jl
src/Tab_PTXpaths_Callbacks.jl

- Added option to compute solidus temperature for the PTX path tab

MAGEMinApp v0.3.5

---

Project.toml
src/MAGEMinApp.jl
src/PTXpaths_functions.jl
src/Tab_Simulation_Callbacks.jl

- corrected the calculation of the solidus and liquidus temperature in the event phase are removed.

MAGEMinApp v0.3.6

---

Project.toml
src/AMR/MAGEMiN_utils.jl
src/MAGEMinApp.jl
src/PhaseDiagram_functions.jl
src/Tab_PhaseDiagram.jl
src/Tab_PhaseDiagram_Callbacks.jl
src/Tab_Simulation.jl
src/Tab_Simulation_Callbacks.jl
src/TraceElement_functions.jl
src/fetch.jl

- Added option to save/load state for phase diagram (Setup tab)

MAGEMinApp v0.3.7

---

Project.toml
src/MAGEMinApp.jl
src/PTXpaths_functions.jl

- corrected display of solvus phase composition for PTX paths

MAGEMinApp v0.3.8

---

Project.toml
src/AMR/MAGEMiN_utils.jl
src/MAGEMinApp.jl
src/PhaseDiagram_functions.jl
src/Tab_PhaseDiagram.jl

- Corrects isocontour minimum, step and maximum values

MAGEMinApp v0.4.1

---

Project.toml
assets/custom.css
src/MAGEMinApp.jl
src/MAGEMinApp_functions.jl
src/PTXpaths_functions.jl
src/PhaseDiagram_functions.jl
src/Tab_Classification.jl
src/Tab_PhaseDiagram.jl
src/Tab_PhaseDiagram_Callbacks.jl
src/Tab_Simulation.jl
src/Tab_Simulation_Callbacks.jl
src/Tab_TraceElement.jl
src/Tab_TraceElement_Callbacks.jl
src/TraceElement_functions.jl
src/appData.jl

- Added option to hide/show isopleths
- Added option to display phase composition when clicking on pie chart

MAGEMinApp v0.5.1

---

Project.toml
src/MAGEMinApp.jl
src/PhaseDiagram_functions.jl
src/Tab_PhaseDiagram_Callbacks.jl
src/appData.jl

- Corrected crash when deleting last isopleth

MAGEMinApp v0.5.3

---

Project.toml
src/MAGEMinApp.jl
src/PhaseDiagram_functions.jl
src/appData.jl

- Corrected undefined variable leading to app crash...

MAGEMinApp v0.5.4

---

Project.toml
src/MAGEMinApp.jl
src/PhaseDiagram_functions.jl
src/Tab_PTXpaths_Callbacks.jl
src/Tab_Simulation_Callbacks.jl
src/Tab_isentropic_Callbacks.jl

- Fixed problem that was not allowing changing the bulk-rock value directly in the bulk tables

MAGEMinApp v0.5.8

---

Project.toml
src/MAGEMinApp_functions.jl
src/PhaseDiagram_functions.jl

- Added full solution phase name in the figure output
- Updated mineral naming to fit THERMOCALC convention
- Corrected issue when deactivating solution phase model

MAGEMinApp v0.6.3

---

src/Tab_Simulation.jl

- further improved accuracy of metapelite, metabasite, igneous and alkaline databases calculations
- added iw buffer to metapelite, metabasite, igneous and alkaline databases
- added prehnite, pumpellyite and pyrophyllite for the metapelite extended databases

MAGEMinApp v0.7.1

---

Project.toml
src/MAGEMinApp_functions.jl

- Corrected recently introduced problem when computing several isopleths and trying to hide field labels

MAGEMinApp v0.8.3

---

Project.toml
src/AMR/MAGEMin_utils.jl
src/PhaseDiagram_functions.jl
src/Tab_Simulation.jl

- Corrected extraction of melt during second event for polymetamorphic T-T diagrams. Water extraction now leaves a tiny amount to be slightly over-saturated.

MAGEMinApp v0.8.6

---

Project.toml
src/appData.jl

- Deactivated unbenchmarked database

MAGEMinApp v0.9.1

---

Project.toml

MAGEMinApp v1.0.3

---

.gitignore
Project.toml
src/MAGEMinApp.jl
src/MAGEMinApp_functions.jl
src/PhaseDiagram_functions.jl
src/Tab_PhaseDiagram.jl
src/Tab_PhaseDiagram_Callbacks.jl
src/Tab_Simulation.jl
src/Tab_TraceElement.jl
src/Tab_TraceElement_Callbacks.jl
src/TraceElement_functions.jl

- Added option to export pseudosections as vector files for each layer (fields, isopleths, reaction lines, labels etc.) 
- Added App mode for starting MAGEMinApp with Julia > 1.12 (by H. Dominguez)

MAGEMinApp v1.0.6

---

Project.toml

- Corrected MAGEMin_dataTE2dataframe function that was crashing

MAGEMinApp v1.0.7

---

Project.toml
src/AMR/MAGEMin_utils.jl
src/MAGEMinApp_functions.jl
src/PhaseDiagram_functions.jl
src/Tab_PhaseDiagram.jl
src/Tab_PhaseDiagram_Callbacks.jl
src/Tab_Simulation.jl
src/Tab_Simulation_Callbacks.jl

- Added “Calculator oxides” option to compute custom oxides isopleths

MAGEMinApp v1.0.8
